### ISSUE TITLE
Loader needed for Webpack

### ISSUE THREAD

**Issue by prescottprue** [gorangajic/react-icons#1]
When attempting to use with Webpack, I get the following error:

<img width="833" alt="screen shot 2015-10-27 at 3 39 36 pm" src="https://cloud.githubusercontent.com/assets/2992224/10770291/df6d339c-7cc0-11e5-8617-8f25c931f258.png">

It seems to be due to not having a loader of some type, but it might be good to include that in the documentation. I am going to experiment with some css/style loaders to see if I can get something working.

**Comment by gorangajic** [comment]
Do you use babel-loader?

**Comment by prescottprue** [comment]
Realizing that is what is probably is due to it erroring on the export. Did I miss that being a requirement somewhere in the docs or is it not in there?

**Comment by KyleAMathews** [comment]
:+1: to a pre-transpiled version

**Comment by gorangajic** [comment]
I have added last night transformed version in /lib and it's on npm. Just need to update docs

**Comment by gorangajic** [comment]
@prescottprue that is also fixed in the new version I was using stateless function components so it was needed to React be global, now it's ussing classes

**Comment by gorangajic** [comment]
https://github.com/gorangajic/react-icons/commit/321f37b2e4ac112eb4c7230a8aaa6e90ee15aaae

**Comment by prescottprue** [comment]
Awesome, thanks for fixing it so fast!
