### ISSUE TITLE
Some fontawesome icons are broken / don't fit their viewport

### ISSUE THREAD

**Issue by Prinzhorn** [gorangajic/react-icons#10]
Correct: https://github.com/gorangajic/react-icons/blob/323e5568347abb61323f75f70e63c346603a263e/icons/fa/repeat.svg

Incorrect: https://github.com/gorangajic/react-icons/blob/323e5568347abb61323f75f70e63c346603a263e/icons/fa/undo.svg
Also incorrect: https://github.com/gorangajic/react-icons/blob/323e5568347abb61323f75f70e63c346603a263e/icons/fa/gear.svg

I don't know how you pull these SVGs in and process them, but something went wrong for some of them.

**Comment by gorangajic** [comment]
some icons in font awesome have more than one, thats why we had broken old icons that were duplicated.

for example
repeat => rotate-right
undo => rotate-left
gear => cog

Now they are removed https://github.com/gorangajic/react-icons/commit/2a3f1bfae88f3e35e24c665ccea8a22d80626f63

**Comment by Prinzhorn** [comment]
I see. How did you decide which ones to keep? E.g. `undo` is the official name an `rotate-left` the alias, but you kept `rotate-left`. http://fontawesome.io/icon/undo/

Is your whole process automated? If so, can't we support aliases? Like `module.exports = require('./undo.js');` inside the `rotate-left.js`?

**Comment by gorangajic** [comment]
it's not all automated, it's look like it took first icon that come in alphabetical order. 

At first I was using [svg-caster](https://github.com/icons8/svg-caster) to get svg icons from the font file, now I use https://icomoon.io/ because I thought that svg-caster was broken  #6

**Comment by Prinzhorn** [comment]
But now 1.0.3 is a breaking change, because some people (including me) already use fa icons which are now removed. We should keep them and automate everything. Discussion here: #11

**Comment by gorangajic** [comment]
:+1:
