### ISSUE TITLE
Upgrade peer-dependencies for react 16

### ISSUE THREAD

**Issue by duro** [gorangajic/react-icons#116]
As title states

**Comment by duro** [comment]
I have tested this, and all works well under react 16, just need to clear up the peer dep warnings

**Comment by mshwery** [comment]
This would be great – I cannot upgrade to 16 until `react-icons` peerDependencies supports as well.

**Comment by mshwery** [comment]
Closed by https://github.com/gorangajic/react-icons/pull/117

**Comment by nwwells** [comment]
Merged #117

**Comment by nwwells** [comment]
@gorangajic will you publish v2.2.6, please?

**Comment by mshwery** [comment]
Would be great to get this published on npm.

**Comment by nwwells** [comment]
published as 2.2.6
