### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by jadedevin13** [gorangajic/react-icons#12]
I'm using **jspm** and the command I issued is 
```bash
jspm install react-icons=npm:react-icons
```
```
warn It's taking a long time to process the dependencies of npm:react-icons@1.0.3.
     This package may need an ignore property to indicate test or example folders for jspm to skip.


err  Error: EMFILE: too many open files, open '/home/jadedevin13/.jspm/packages/npm/react-icons@1.0.3/md/markunread.js'
         at Error (native)

warn Installation changes not saved.
```

**Comment by jadedevin13** [comment]
I realize this is issue is not about the package react-icons but npm as the package manager.

BTW

I just came back to solve it on my own by a handful of commands.
```
ulimit -n 
```
This didn't solve the issue. I have to edit the */etc/security/limits.conf* file and add the following
```
@user    hard    nofile           65535
@user    soft    nofile           65535
```

**Comment by gorangajic** [comment]
closing because it's not related to react-icons, it's probably something wrong with `jspm`
