### ISSUE TITLE
Include Ionicon

### ISSUE THREAD

**Issue by rblakeley** [gorangajic/react-icons#17]
It would be really nice to have the [Ionicon](http://ionicons.com/) set in this library.

I believe I added the proper source files in #13.

**Comment by maxekman** [comment]
I would also like to see this merged.

**Comment by gorangajic** [comment]
Sorry guys was busy with some stuff and I wanted to solve #11 before adding new icon set, so everything can be more automated. 

If no one else tackle this I will try to do it over the weekend

**Comment by Secretmapper** [comment]
+1

**Comment by gorangajic** [comment]
They are added now
