### ISSUE TITLE
change color on hover

### ISSUE THREAD

**Issue by tgoldenberg** [gorangajic/react-icons#20]
Hi, I am using Radium to add `:hover` styles, but when I add a new color on hover, it doesn't appear. Any idea how I can achieve this effect? Thanks!

**Comment by tgoldenberg** [comment]
Ended up refactoring the button to a separate component with a `hover` state that modifies the color, but wondering if there's any easier way to do this...

**Comment by Prinzhorn** [comment]
Can you share some code? Did you try changing `fill` and well as `color`? Not sure to which element radium adds the style. If it's the parent of the <svg> then `color` is the correct property. When manipulating the <svg> directly then `fill` needs to be changed.

**Comment by tgoldenberg** [comment]
okay, I got it to work with a `hover` state, but I'll give it a try this way too. Thanks
