### ISSUE TITLE
Wrap in div with class

### ISSUE THREAD

**Issue by mrberggg** [gorangajic/react-icons#21]
Would be great if each icon would be wrapped in a div with a class, e.g. .react-icon, so that global icon styles could be applied. Unless I'm missing something obvious, you currently have to either have global svg styles or separate styles for each usage.

**Comment by gorangajic** [comment]
I think that you can pass `className` for example <Icon className="react-icon" />

**Comment by mrberggg** [comment]
@gorangajic Ok but wouldn't it be nice to have project-wide styles? E.g. setting a default icon color?

**Comment by ezekg** [comment]
I would go for a `<span>` if you do implement this, because a `<div>` can't be nested under `<p>` tags. To solve this issue, I usually just create an `<Icon />` component that is essentially just wrapping the icon in a `<span>` so that I can apply the classes I need, just as a reference to what @gorangajic is talking about.

```cjsx
React = require "react"

module.exports =
class Icon extends React.Component
  @defaultProps = {
    set: "md"
  }
  @propTypes = {
    set: React.PropTypes.string
    symbol: React.PropTypes.string.isRequired
  }

  constructor: ->
    @state = {}

  render: ->
    icon = try
             @icon = require "react-icons/lib/#{@props.set}/#{@props.symbol}"
             <@icon />

    <span className="icon">
      {icon}
    </span>
```

Use like,

```cjsx
<Icon symbol="launch" /> # Default set is "md"

# Or specify a different set...
<Icon symbol="home" set="fa" />
```

**Comment by mvaivre** [comment]
@ezekg I try to do exactly the same as you, and I've a crazy error. Here is my code. 

```coffeescript
React = require 'react'

@IconButton = ( props ) ->
  icon = try
    Icon = require("react-icons/lib/md/#{props.icon}")
    <Icon fill={props.fill}/>
  catch error
    console.log(error)

  <button onClick={props.onClick}>
    {icon}
  </button>

IconButton.propTypes =
  icon: React.PropTypes.string # Name of md icon
  fill: React.PropTypes.string
  onClick: React.PropTypes.func
```

String interpolation with the icon name gives me `Cannot find module 'react-icons/lib/md/save'`

If I hardcode the path `react-icons/lib/md/save` without string interpolation, it works.

Did you get this king of problem before?

**Comment by ezekg** [comment]
I'm not entirely sure. I'm doing that in an Electron app, so maybe Node behaves differently inside of it.

**Comment by Prinzhorn** [comment]
@mvaivre `require` are resolved at compile time (e.g. when you run browserify/webpack, not when the code is run in the browser). They can't be dynamic as far as I know.

**Comment by mvaivre** [comment]
@ezekg: Ah, you're using electron! @Prinzhorn Right, of course. Thank you both for your answers.
So, it's seems hard to create a component like mine, that only takes the icon name to "dynamically" render an icon? Or do you have another solution to achieve that?

**Comment by Prinzhorn** [comment]
@mvaivre create a `icons.js` which exports all icons you know you will need

```js
modules.exports = {
    "foo": require("react-icons/lib/md/foo"),
    "bar": require("react-icons/lib/md/foo"),
    "foo": require("react-icons/lib/md/foo")
};
```

and in your component

```js
var iconsByName = require("./icons.js")

//...later....

Icon = iconsByName[props.icon];
```

**Comment by mvaivre** [comment]
@Prinzhorn Alright, this needs a bit more work than expected, but that works! Thanks for your reactivity!

**Comment by gorangajic** [comment]
I have just merged https://github.com/gorangajic/react-icon-base/pull/6 you can use `context` to style icons
