### ISSUE TITLE
FontAwesome times icon missing

### ISSUE THREAD

**Issue by felipeleusin** [gorangajic/react-icons#26]
After the update to 1.0.5 the FontAwesome times icon went missing. I've tried fixing but can't seem to build the project getting a maximum calls stack exceeded.

http://fortawesome.github.io/Font-Awesome/icon/times/

**Comment by gorangajic** [comment]
Sorry, but some icons have aliases and some icons are named by their alias instead of their real name
that icon in react-icons is called `close`

**Comment by felipeleusin** [comment]
Ah thanks! My bad!
