### ISSUE TITLE
1.0.5 broke our build

### ISSUE THREAD

**Issue by andreypopp** [gorangajic/react-icons#27]
After you updated babel to version 6 and released `1.0.5` we had our builds broken, because we consumed icons like this:
```
var Icon = require('react-icons/lib/fa/plus');
```
now it should be:
```
var Icon = require('react-icons/lib/fa/plus').default;
```

The fix would be to add https://www.npmjs.com/package/babel-plugin-add-module-exports plugin to the build config and release a new patch version.

**Comment by gorangajic** [comment]
can you try now?

**Comment by andreypopp** [comment]
Awesome, thanks!
