### ISSUE TITLE
Icons are missing from lib/

### ISSUE THREAD

**Issue by indeyets** [gorangajic/react-icons#28]
We used to manually include icons from `lib/` folder as described in readme, but 1.0.6 has less icons than 1.0.3 had. Probably a build issue.

specifically, we need `react-icons/lib/md/favorite-border`

**Comment by gorangajic** [comment]
I have added them back in 2.0.0

**Comment by tnrich** [comment]
There still seems to be some missing icons in 2.0

Specifically I'm not able to find:
`lib/go/input-checked`

Thanks!
