### ISSUE TITLE
Material Design: open-in-browser and open-in-new only work with underscores

### ISSUE THREAD

**Issue by ezekg** [gorangajic/react-icons#29]
The Material Design icons `open-in-browser` and `open-in-new` do not display unless called like `open-in_browser` and `open-in_new`, respectively. There are duplicated files for each of those in [the Material Design icon directory](https://github.com/gorangajic/react-icons/tree/master/md). Is there a reason for this? Can we standardize the way icons are named, so that they always use kebab-case as opposed to mixed?

**Comment by gorangajic** [comment]
Thank you, it's fixed now in v2.0.1
