### ISSUE TITLE
Hard coded fill="#444" in icons

### ISSUE THREAD

**Issue by elado** [gorangajic/react-icons#30]
https://github.com/gorangajic/react-icons/commit/e318058c0d4553ddf8f3bbdabcdbc414350f861a introduced `fill="#444"` in all icons. This prevents coloring with `currentColor`.

**Comment by ivoanastacio** [comment]
+1

**Comment by Prinzhorn** [comment]
This happened before in #9. I think this process needs to be automated to prevent this in the future.

**Comment by gorangajic** [comment]
sorry guys my bad this is now fixed in v2.0.1 06f5476
