### ISSUE TITLE
Missing fa icons

### ISSUE THREAD

**Issue by Prinzhorn** [gorangajic/react-icons#33]
I updated to react 15 and react-icons 2. The following are missing now.

```
Error: Cannot find module 'react-icons/lib/fa/times'
Error: Cannot find module 'react-icons/lib/fa/link'
Error: Cannot find module 'react-icons/lib/fa/gear'
Error: Cannot find module 'react-icons/lib/fa/undo'
```

**Comment by gorangajic** [comment]
Some icons have aliases, it's the same icon just different name

`times` => `close`
`link` => `chain`
`gear` => `cog`
`undo` => `rotate-left`

**Comment by Prinzhorn** [comment]
Thanks! Hm, yeah. We had that discussion before. But `chain` is an alias for `link`. Not the other way round. Also I still think react-icons should alias them as well then. Otherwise it's a guessing game.
