### ISSUE TITLE
Issue with importing icons

### ISSUE THREAD

**Issue by bsr203** [gorangajic/react-icons#4]
Hi,
I could be terribly overlooking something, but none of the import method in the doc didn't work for me.

1. import FaBeer from 'react-icons/fa/FaBeer';

```
Module not found: Error: Cannot resolve module 'react-icons/fa/FaBeer' in /Users/bsr/testclient/src/
23:04:46 f +2ms      resolve module react-icons/fa/FaBeer in /Users/bsr/testclient/src/
23:04:46 f +2ms        looking for modules in /Users/bsr/testclient/node_modules
23:04:46 f +11ms         resolve 'file' or 'directory' fa/FaBeer in /Users/bsr/testclient/node_modules/react-icons
23:04:46 f +1ms            resolve file
23:04:46 f +0ms              /Users/bsr/testclient/node_modules/react-icons/fa/FaBeer doesn't exist
23:04:46 f +1ms              /Users/bsr/testclient/node_modules/react-icons/fa/FaBeer.webpack.js doesn't exist
23:04:46 f +0ms              /Users/bsr/testclient/node_modules/react-icons/fa/FaBeer.web.js doesn't exist
23:04:46 f +1ms              /Users/bsr/testclient/node_modules/react-icons/fa/FaBeer.js doesn't exist
23:04:46 f +8ms              /Users/bsr/testclient/node_modules/react-icons/fa/FaBeer.json doesn't exist

```

2.     import {MdCancel, MdChat, MdCheck} from 'react-icons/md';

./~/react-icons/md.js
23:05:17 f +0ms      Module parse failed: /Users/bsr/testclient/node_modules/react-icons/md.js Line 1: Unexpected token
23:05:17 f +0ms      You may need an appropriate loader to handle this file type.
23:05:17 f +1ms      | export Md3dRotation from './md/3d-rotation';
23:05:17 f +0ms      | export MdAccessAlarm from './md/access-alarm';
23:05:17 f +1ms      | export MdAccessAlarms from './md/access-alarms';

only way I could work is changing the `package.json` of this project in my `node_modules` to point to the built version
  "main": "icons.js", ->    "main": "lib/icons.js",

I do not want to include node_modules to my webpack source directories (even though I could selectively include just this package) as it is hard to maintain and the build could be slow.

Also, there are lots of duplicate files in the npm package. the icon files are included in the src format, then the built version in `lib` and also a `dist` folder with only `fa` icons in it. Can you please just keep the `lib`.

It is a great package and appreciate your effort on this.
Cheers.
bsr

**Comment by gorangajic** [comment]
can you try now I have updated ```"main"```` to point to lib/icons and added ```"jsnext:main"``` to point to es6 module

by [default](http://babeljs.io/docs/usage/require/#usage) babel ignore ```node_modules``` so if you don't want to change that settings you will need to use files from the ```./lib```

```dist``` folder is removed I have been testing something and it was published by accident

**Comment by bsr203** [comment]
thanks.. it works.. to import one icon from lib, the following works

`import Mail from 'react-icons/lib/md/mail'` or ``import MdMail from 'react-icons'`

**Comment by christchron** [comment]
can you tell me how to fix this? i don't really understand what to do to fix this. Thank you.

**Comment by zhenyulin** [comment]
I'm having some issues on the module resolve during the docker build while using the suggested pattern ```import IoAndroidCall from 'react-icons/lib/io/android-call';```

Does it has something to do with webpack import v.s. babel module import?

**Comment by skumblue** [comment]
@christchron you must call the **lib** folder to import.

Look at:
use this `import Mail from 'react-icons/lib/fa/mail'` instead `import Mail from 'react-icons/fa/mail'`.

**Comment by KevinKons** [comment]
I am using `import CalendarIcon from 'react-icons/lib/fa/calendar-plus-o` but i'm still having the error

Failed to compile.

./src/components/App.js
Module not found: Can't resolve 'react-icons/lib/fa/calendar-plus-o' in 'C:\Users\Avell\Documents\GitHub\CursoReactUdacity\udacimeals\src\components'

**Comment by dsmartins98** [comment]
@KevinKons You should import the module as follows: `import {FaCalendarPlus} from 'react-icons/fa'`
