### ISSUE TITLE
Unable to set individual icon color if reactIconBase context is set.

### ISSUE THREAD

**Issue by sammkj** [gorangajic/react-icons#41]
I have the following context:

```
getChildContext() {
    return {
      reactIconBase: {
        color: COLOR_TEXT_PRIMARY,
        size: 24,
      },
  }
```

and the following icon color doesn't display correctly:

```
<MdClear color="#ffffff" />
```

Screenshots:
![image](https://cloud.githubusercontent.com/assets/9153498/16286631/5dafa5fc-38a3-11e6-8bf6-1727e10c9664.png)

![image](https://cloud.githubusercontent.com/assets/9153498/16286650/78eecc4e-38a3-11e6-9a6b-5dc302a3b6eb.png)

![image](https://cloud.githubusercontent.com/assets/9153498/16286660/89d82262-38a3-11e6-985c-f02995d1a6fb.png)

**Comment by bentatum** [comment]
this _should_ be fixed via v2.2.0
