### ISSUE TITLE
Icons seem deformed

### ISSUE THREAD

**Issue by jsierles** [gorangajic/react-icons#6]
Here's a screenshot. See how the circles are deformed? What could cause this?

http://d.pr/i/XBAY

**Comment by gorangajic** [comment]
they are scaled maybe that is the problem I will try to fix it by using larger viewBox

**Comment by jsierles** [comment]
I'm just using the 'size' property. Is that what you mean by 'scaled'?

**Comment by gorangajic** [comment]
I have resized them so they all have the same size for [react-svg-morph](https://github.com/gorangajic/react-svg-morph) but apparently they got deformed in the process. Will try to find some time tomorrow and fix it

**Comment by jsierles** [comment]
Cool. thanks for the update!

**Comment by jsierles** [comment]
Can I help with this issue

**Comment by gorangajic** [comment]
sorry @jsierles forget about this. Are only Font Awesome icons deformed or just that one? I have update them so can you check now? 

```npm install react-icons@0.3.0```

process for this goes something like this 

- used [svg-caster](https://github.com/icons8/svg-caster/) to export svg from the webfont

```svg-caster --svg-font fontawesome-webfont.svg --svg-font-css ../css/font-awesome.css --out-svg ./svg --pretty```
- use [svg-scale](https://github.com/morlay/svg-scaler) to scale icon to 40x40 
- copy exported and scaled svg icons to `react-icons/icons/fa/`
- run `npm run build`

**Comment by gorangajic** [comment]
svg-scaler deformed icons by rounding path
https://github.com/morlay/svg-scaler/blob/master/lib/SVGTranslator.js#L125
