### ISSUE TITLE
Suggestion react-native-icons package.

### ISSUE THREAD

**Issue by tracker1** [gorangajic/react-icons#62]
Would be interesting to see a `react-native-icons` package that re-uses these same svg icons... I know this probably need to be used with [react-native-svg](https://github.com/brentvatne/react-native-svgkit) with a transform to match those components...  I would suggest publishing the output as a separate package only to avoid the react-native option...  Not sure about react-native-web as an option either...

**Comment by gorangajic** [comment]
It would be difficult because `svg` elements are treated as `View` components not `Text`. And you can't insert `View` component into `Text`. So it will be impossible to do something like

```jsx
const Awesome = () => (
    <View style={{ flex: 1 }}>
        <Text>I like to drink <FaBeer /></Text>
    </View>
);
```

[react-native-vector-icons](https://github.com/oblador/react-native-vector-icons) handle that case already
