### ISSUE TITLE
add a unique class for each <svg>

### ISSUE THREAD

**Issue by brillout** [gorangajic/react-icons#65]
E.g. `<svg class="ri ri-fa-star" .../>` for the `fa-star` icon.
So that adjustments can easily be implemented.

**Comment by bentatum** [comment]
We can totally discuss doing this, but for now you should be able to accomplish whatever you need to do using composition.

```
<div class="ri ri-fa-star">
  <svg />
</div>
```

**Comment by bentatum** [comment]
@gorangajic thoughts on this?

**Comment by brillout** [comment]
It's actually what I'm doing right now but wrapping each icon individually is a bit cumbersome.

It seems to me that there are more important tickets though, e.g. https://github.com/gorangajic/react-icons/issues/66

Thanks @bentatum for your work on this, I like this library a lot

**Comment by bentatum** [comment]
I see what you mean. We'll keep it on the list.

For now, you could also create a component that does the wrapping once for you.

```
// CustomIcon.js
import Icon from 'react-icons/lib/io/arrow'
export default ({ className, ...props }) =>
  <div className={className}>
    <Icon {...props} />
  </div>
```

and then use it like this:

```
// App.js
import Icon from './CustomIcon'
export default () => <Icon className='ri ri-fa-star' />
```

**Comment by bentatum** [comment]
I'm going to close this for now. Feel free to submit a PR to propose any desired functionality you may have and we'll gladly consider it!
