### ISSUE TITLE
How to change size and color for icon

### ISSUE THREAD

**Issue by NgKhanh** [gorangajic/react-icons#67]
Hello, I read document I see this code
`<Icon size={30} color='aliceblue' style={{ ... }} />`

But I dont understand how to use this, e.x I want to user MdStar with size:2em, color=blue
`<MdStar  size={2} color="blue">`

Is it ? Pls give more code

**Comment by nguyenmanh1507** [comment]
convert em to pixel and set color for parent el. ex:
parent element font-size = 16px => 2em = 32px
```
<div style={{color: 'blue'}}>
  <MdStar size={32} />
</div>
```

**Comment by bentatum** [comment]
The size prop only accepts pixels as an integer value. The color prop should work, is it not for you?

**Comment by NgKhanh** [comment]
Thanks, I did it

**Comment by danieli45** [comment]
thanks!

**Comment by jrbytes** [comment]
> convert em to pixel and set color for parent el. ex:
> parent element font-size = 16px => 2em = 32px
> 
> ```
> <div style={{color: 'blue'}}>
>   <MdStar size={32} />
> </div>
> ```

import { FaPlusSquare } from 'react-icons/fa'
<FaPlusSquare viewBox='0 30 448 512' />

**Comment by jrbytes** [comment]
> convert em to pixel and set color for parent el. ex:
> parent element font-size = 16px => 2em = 32px
> 
> ```
> <div style={{color: 'blue'}}>
>   <MdStar size={32} />
> </div>
> ```

Now
```
import { FaPlusSquare } from 'react-icons/fa'
<FaPlusSquare viewBox='0 30 448 512' />
```

**Comment by imrishav** [comment]
Easiest way to Change style of icon is using this

`<FaThumbsDown size={30} style={{ fill: 'black' }} />`

**Comment by AbrahamLawson** [comment]
> style={{ fill: 'black' }}

It works well. Many thanks

**Comment by andreferreiradaweb** [comment]
How to set :hover value on react-icons ?

**Comment by greatertomi** [comment]
> How to set :hover value on react-icons?

I have this same problem. How do we change the size of react-icons during hover?

**Comment by greatertomi** [comment]
>How to set :hover value on react-icons?

`&:hover {
    height: 30px;
    width: 40px;
  }`

this increases the size during hover

**Comment by Trxuxv** [comment]
> Hello, I read document I see this code
> `<Icon size={30} color='aliceblue' style={{ ... }} />`
> 
> But I dont understand how to use this, e.x I want to user MdStar with size:2em, color=blue
> `<MdStar size={2} color="blue">`
> 
> Is it ? Pls give more code

it rlly helped :') thk

**Comment by GNVageesh** [comment]
`<FaFacebookMessenger size={100} color={"yellow"} />`

Adds a size of 100 and color yellow to the FacebookMessenger icon

**Comment by Nishanth-sebastin** [comment]
> 

Thanks itz worked

**Comment by robbie9715** [comment]
thank you!

**Comment by omarmazin** [comment]
`<Icon size={10}/>`

**Comment by smileyismail** [comment]
some icons do not accept color so try different one

**Comment by sudo-001** [comment]
> Easiest way to Change style of icon is using this
> 
> `import { FaThumbsDown, FaThumbsUp } from 'react-icons/fa';` `<FaThumbsDown size={30} style={{ fill: 'black' }} />`

Thanks

**Comment by Nirdosh2004** [comment]
Without even using Tailwindcss 
``<CgRowFirst size={30} />``

**Comment by tisonkun** [comment]
@kamijin-fanta Not sure if we can include these docs in the doc page.

I don't find the source code of the site, or else I can try to write it down.
