### ISSUE TITLE
stateless (Pure) components

### ISSUE THREAD

**Issue by jdeniau** [gorangajic/react-icons#69]
react-icons does not seems to care about stateless components. 

React now provide a ["PureComponent"](https://facebook.github.io/react/docs/react-api.html#react.purecomponent) class making your component Pure. Another solution is to write components as simple function as said [in the 0.14](documentation).

The advantage of the first solution is that it will be quite esay to update react-icons (sed shoud work fine), but was introduced in 15.3 (and you may not want to loose the compatibility). It may be compatible using [react-addons-shallow-compare](https://facebook.github.io/react/docs/shallow-compare.html) though.

The second solution works since 0.14 but may not be as easy to migrate (class => function).

First of all : will you be OK with that move ? If so, what solution do you prefer ?

**Comment by bentatum** [comment]
We definitely do care. The update for this is in master. https://github.com/gorangajic/react-icons/blob/master/bin/create.js#L49

I'll publish a new version soon.

**Comment by jdeniau** [comment]
Oh OK I did not see that, I just looked in the Icon folder. Will test it
when it's released.

Thank you for your project by the way

**Comment by bentatum** [comment]
No problem @jdeniau! Thanks for contributing. The update should be in v2.2.2.
