### ISSUE TITLE
color / theme

### ISSUE THREAD

**Issue by bsr203** [gorangajic/react-icons#7]
Hi,

It was easy to change the color of webfont, for example the font color of a primary button was white in twitter bootstrap and the font follows the same. How to do the same with an svg icon? your expertise and a example would help :-)

https://github.com/google/material-design-icons/issues/58
http://stackoverflow.com/questions/26892628/set-background-color-of-svg-material-design-icons
http://stackoverflow.com/questions/27847226/use-md-icon-to-set-the-color-of-svg

**Comment by Prinzhorn** [comment]
my pull request just landed https://github.com/gorangajic/react-icon-base/pull/1 so this should soon work with react-icons as well

**Comment by bsr203** [comment]
@Prinzhorn cool.. didn't know that it is that easy.. thanks.

**Comment by tnrich** [comment]
@Prinzhorn would you mind giving a bit more of a description of what exactly needs to be done to style the icons with a given color?

**Comment by Prinzhorn** [comment]
With the latest version they simply use the same color as the text. So if your have a `color:` declaration for the wrapper element (like `<button>` or `<span>`) or any parent then the icon uses the same color as the text.

You can still overwrite this using the `fill` prop

**Comment by tnrich** [comment]
hmm neither of those are quite working for me.. Could I be on an older version?

**Comment by Prinzhorn** [comment]
This commit broke it https://github.com/gorangajic/react-icons/commit/9ee354c2461d9986191f885a82ff3d27e599b370

**Comment by Prinzhorn** [comment]
Check out 0.3.1 to see how its supposed to work

**Comment by tnrich** [comment]
Oh, interesting. So for the time being I can go back a few versions until it's fixed? Thanks for the help too btw :+1:

**Comment by Prinzhorn** [comment]
Kind of. What you don't get is icons which scale to the size of the text, you need to set the `size` prop to `1em` manually if you want that. But you get the color thing.
