### ISSUE TITLE
How to use import *

### ISSUE THREAD

**Issue by EddyTheDove** [gorangajic/react-icons#72]
Hello, 
I could not find anywhere in the documentation and on google how to use
`import * as FontAwesome from 'react-icons/fa'` in the render fonction. 

Thank you for understanding.

**Comment by bentatum** [comment]
this should work:

`import * as FontAwesome from 'react-icons/lib/fa'`

**Comment by EddyTheDove** [comment]
Sorry that is how to import... 
You don't show any example to use it in a tag.

**Comment by bentatum** [comment]
Sorry for the confusion. I'll do my best to clarify that in the readme.

**Comment by bentatum** [comment]
Ah, I see what you mean. Just `console.log(FontAwesome)` and it will show you all of the names of the icons. And you should be able to use it in a tag like this: `<FontAwesome.FaAlignCenter />`.

The reason we import directly from the lib/icon source is because it reduces bundle size. If you import all from FontAwesome, you're importing hundreds of icons at once which is probably not ideal.

**Comment by EddyTheDove** [comment]
Thank you very much. That's indeed what I was looking for. Thanks

**Comment by andrii-m** [comment]
I have an error when tries to import an Icon in following ways
`import { FaBeer } from 'react-icons/fa/';`
`import * as FontAwesome from 'react-icons/fa/';`

![unspecified](https://cloud.githubusercontent.com/assets/2855143/23344115/61744f62-fc7f-11e6-846d-68715b8a4bcf.png)


I think there should be something like `export { default as Fa500px } from './500px';`

**Comment by metasean** [comment]
@andrii-m - I think the documentation is just problematic and needs to be corrected.  The following ways should work:

`npm install react-icons --save` then

**To import all icons, and use a specific one:**
```
// inside component's file
// !!! note that the path differs from react-icons documentation !!!
import * as FontAwesome from 'react-icons/lib/fa'

// inside the component's render function
// note that you use dot notation within the JSX to pick the appropriate icon
<FontAwesome.FaBeer />
```

**To import and use a single icon:**
```
// inside component's file
import FaBeer from 'react-icons/lib/fa/beer'

// inside the component's render function
<FaBeer />
```

**Comment by saoud-ahmed-khan** [comment]
import * as Fa from "react-icons/fa";
you can  just simply import it like this above.

<Fa.FaCar/>
and call it in that fashion. hope it works for you.
