### ISSUE TITLE
Merge #63 breaks enzyme's find()

### ISSUE THREAD

**Issue by carlodicelico** [gorangajic/react-icons#75]
#63 breaks [enzyme's ShallowWrapper API's find()](http://airbnb.io/enzyme/docs/api/ShallowWrapper/find.html), which is looking for a function name. Enzyme uses the function's name attribute to facilitate easier lookup of components rendered in a tree. 

Proposing this, so that the export is a named function.

```javascript
var component = `
import React from 'react'
import Icon from 'react-icon-base'

const ${name} = props => (
    <Icon viewBox="${viewBox}" {...props}>
        <g>${iconSvg}</g>
    </Icon>
)

export default ${name}`
```

**Comment by bentatum** [comment]
I think that's reasonable. Do you mind submitting a pull request?

**Comment by carlodicelico** [comment]
[Done](https://github.com/gorangajic/react-icons/pull/76)!

**Comment by bentatum** [comment]
😎  Cool, thanks! I'll give it a spin this afternoon and publish a new version if all checks out.

**Comment by bentatum** [comment]
2.2.3 resolve this. thanks again!
