### ISSUE TITLE
Helper components to turn them into buttons

### ISSUE THREAD

**Issue by tnrich** [gorangajic/react-icons#8]
Hey there, I think it'd be nice if there were a helper component to turn these suckers into nicely formed buttons. I'm not sure if people already have something they're already using, so I thought I'd ask. 

Something like this was what I was thinking: 
```
<CircularButton>
          <ChevronLeft>
          </ChevronLeft>
</CircularButton>

// and/or

<ButtonWrapper>
          <ChevronLeft>
          </ChevronLeft>
        </ButtonWrapper>
```

**Comment by Prinzhorn** [comment]
What would the benefit be? Don't you want the buttons to match the design of the rest of the app? Your app likely already has a button component.

I personally think it's out of scope for react-icons, because it does one thing and does it well, which is inlining SVG icons as unopinionated as possible.

**Comment by tnrich** [comment]
Sounds good, I was mostly looking for already built buttons that work well with your svg set as the default browser <button/> element didn't work very well with it. One I found is this: https://github.com/zippyui/react-button. You could potentially link to it, or just having this issue would probably be enough to point others toward those buttons. I'd still be interested in seeing other button sets people know of that work well with this library.

**Comment by Prinzhorn** [comment]
> as the default browser element didn't work very well with it

Now I'm curious. I've set up a demo project with this simple code (no CSS at all)

```js
var React = require('react');
var ReactDOM = require('react-dom');
var FaBeer = require('react-icons/lib/fa/beer');

ReactDOM.render(
	<button type='button'>
		<FaBeer /> Hey you, beer me. Beer us together, naturally.
	</button>,
	document.getElementById('example')
);
```

Here are Screenshots of Chromium and Firefox (on Ubuntu, but I assume native buttons on other platforms work equally well).

![screenshot from 2015-12-04 10 57 21](https://cloud.githubusercontent.com/assets/679144/11586862/2a81c032-9a76-11e5-8803-be51a57504b1.png)
![screenshot from 2015-12-04 10 57 29](https://cloud.githubusercontent.com/assets/679144/11586863/2a872572-9a76-11e5-9e92-c0c4e4d6d4e9.png)

**Comment by tnrich** [comment]
For me it was when I tried to make a circular button using border-radius: '50%' that things got a little wonky. 

But that probably could have been solved without going to another library. But using another lib worked so I went with that.
