### ISSUE TITLE
Is there a babel-plugin cherry pick module like babel-plugin-lodash does?

### ISSUE THREAD

**Issue by gutenye** [gorangajic/react-icons#84]
Is there a babel plugin that transfrom

```
import { MdCheck } from 'react-icons/lib/md'
```

to

```
import MdCheck from 'react-icons/lib/md/check'
```

webpack2 tree shaking does not solve it, for you still need import all icons in development (which is large and slow build).

I did a few search, and found some plugins may help:

- https://bitbucket.org/amctheatres/babel-transform-imports
- https://github.com/ant-design/babel-plugin-import

**Comment by gutenye** [comment]
Can use babel-transfrom-imports https://bitbucket.org/amctheatres/babel-transform-imports/commits/47089e91b767d4762b0d1f67551407e6d0c4e387

**Comment by zhenyulin** [comment]
@gutenye How do you actually config the plugin for this library? I found it a bit tricky as it involves sub-module in the path, e.g. the `md`

**Comment by gutenye** [comment]
@zhenyulin I created a small library for it, please check https://github.com/gutenye/transform-imports-react-icons
