### ISSUE TITLE
Usage with Create React App

### ISSUE THREAD

**Issue by corydeppen** [gorangajic/react-icons#85]
Trying to use `import FaPlus from 'react-icons/fa/plus'` in a Create React App project fails with the following:

```
Module parse failed
You may need an appropriate loader to handle this file type.
```

If I understand what I've read from browsing this and other issue lists, it's due to the CRA Webpack config trying to use the file-loader instead of the babel-loader. For CRA projects that haven't ejected, it seems like the alternative is to use the compiled module with `import FaPlus from 'react-icons/lib/fa/plus'`.

Would it be possible to mention the recommended approach in the readme/docs when working in a project that uses CRA?

**Comment by noosxe** [comment]
I'm trying to use library without Create React App, using babel-loader in webpack2 config and it does not work anyway!
Interesting to know what can be the cause.

**Comment by mergebandit** [comment]
It sort of hints at this in the Usage section of ReadMe ... 

But change your import to `import FaPlus from 'react-icons/lib/fa/plus` and it will work with CRA. Doing so right now.

**Comment by paniclater** [comment]
Confirmed this works with create react app as documented. Thank you for an amazing project!

**Comment by mariacheline** [comment]
When I try to import multiple icons I get error `MDCancel' is not defined  react/jsx-no-undef`
Importing `import {MdCancel, MdChat, MdCheck} from 'react-icons/md';`
Also tried `import {MdCancel, MdChat, MdCheck} from 'react-icons/lib/md';` but nothing works.

**Comment by nimaiwalsh** [comment]
Do you have to import each individual icon required using the above method in CRA?

You can't use `import {MdCancel, MdChat, MdCheck} from 'react-icons/md';` as an example?

**Comment by nwwells** [comment]
Yes you can, but from react-icons/lib/md
