### ISSUE TITLE
Regression, fill prop is ignored

### ISSUE THREAD

**Issue by Prinzhorn** [gorangajic/react-icons#9]
Commit https://github.com/gorangajic/react-icons/commit/9ee354c2461d9986191f885a82ff3d27e599b370 introduced a `fill` attribute on most path elements which means using the `fill` prop on the component does not work anymore.

**Comment by tnrich** [comment]
:+1:

**Comment by gorangajic** [comment]
https://github.com/gorangajic/react-icons/commit/494eac504afa6fe7ccf5af4fd1c1512b2b5b315f

**Comment by Prinzhorn** [comment]
Thank you! Works great again.

**Comment by gorangajic** [comment]
Thank you for help

**Comment by tnrich** [comment]
Thanks!
