### ISSUE TITLE
Accessing PropTypes via the main React package is deprecated

### ISSUE THREAD

**Issue by Carduelis** [gorangajic/react-icons#93]
Hello, since React v15.x React.PropTypes is deprecated, instead we should use independent package 'prop-types';
So, in place of this
```javascript
var _react = require('react');
// several lines of code
IconBase.propTypes = {
  color: _react.PropTypes.string,
  size: _react.PropTypes.oneOfType([_react.PropTypes.string, _react.PropTypes.number]),
  style: _react.PropTypes.object
};
```
you need to put
```javascript
var _react = require('react');
var PropTypes = require('prop-types');
// several lines of code
IconBase.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([_react.PropTypes.string, _react.PropTypes.number]),
  style: PropTypes.object
};
```
... or smth with using underscore like _propTypes

**Comment by sebastienbarre** [comment]
This was fixed last week in [`react-icon-base`](https://github.com/gorangajic/react-icon-base/commits/master), which I believe is the framework `react-icons` leverages; unfortunately `react-icons` [still uses 2.0.4](https://github.com/gorangajic/react-icons/blob/master/package.json#L63).

**Comment by DrYSG** [comment]
is this on the list of things to fix yet? Seems straightforward.
